# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim, a matriz é uma lista de listas, onde cada linha representa um objeto composto unidimensional

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [2]:
lista_genes = ['BRCA1', 'TP53', 'EGFR', 'CHEK2', 'PTEN']
print(lista_genes)
lista1 = [5, 'BR', 1, False]
lista2 = [4, 'TP', 0, False]
lista3 = [4, 'EG', 0, False]
lista4 = [5, 'CH', 0, False]
lista5 = [4, 'PT', 0, False]
print(lista1, lista2, lista3, lista4, lista5)

matriz_genes = [lista1, lista2, lista3, lista4, lista5]
print(matriz_genes)

['BRCA1', 'TP53', 'EGFR', 'CHEK2', 'PTEN']
[5, 'BR', 1, False] [4, 'TP', 0, False] [4, 'EG', 0, False] [5, 'CH', 0, False] [4, 'PT', 0, False]
[[5, 'BR', 1, False], [4, 'TP', 0, False], [4, 'EG', 0, False], [5, 'CH', 0, False], [4, 'PT', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [7]:
import numpy as np
matriz_genes_np = np.array(matriz_genes)
matriz_genes_np

array([['5', 'BR', '1', 'False'],
       ['4', 'TP', '0', 'False'],
       ['4', 'EG', '0', 'False'],
       ['5', 'CH', '0', 'False'],
       ['4', 'PT', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [10]:
matriz_genes[2]

[4, 'EG', 0, False]

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [33]:
for gene in lista_genes:
    print('hu' in gene)

False
False
False
False
False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [10]:
lista_genes = ['BRCA1', 'TP53', 'EGFR', 'CHEK2', 'PTEN']
print(lista_genes[1][:2], lista_genes[1].count('A'))
print(lista_genes[3][:2], lista_genes[3].count('A'))

TP 0
CH 0

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [1]:
import pandas as pd

dicionario_genes = {
    'BRCA1': [5, 'BR', 1, False],
    'TP53': [4, 'TP', 0, False],
    'EGFR': [4, 'EG', 0, False],
    'CHEK2': [5, 'CH', 0, False],
    'PTEN': [4, 'PT', 0, False]
}

df = pd.DataFrame(dicionario_genes).T

df.columns = ['numero de caracteres', 'iniciais', 'qtd_a', 'se_tem_hu']

print(df)

      numero de caracteres iniciais qtd_a se_tem_hu
BRCA1                    5       BR     1     False
TP53                     4       TP     0     False
EGFR                     4       EG     0     False
CHEK2                    5       CH     0     False
PTEN                     4       PT     0     False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [7]:
df[['numero de caracteres', 'qtd_a']]

      numero de caracteres qtd_a
BRCA1                    5     1
TP53                     4     0
EGFR                     4     0
CHEK2                    5     0
PTEN                     4     0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [8]:
df.loc[['BRCA1', 'EGFR'], ['se_tem_hu',]]

      se_tem_hu
BRCA1     False
EGFR      False

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [15]:
import pandas as pd
df = pd.read_csv('data.csv')
num_linhas = len(df)
classes_colunas = list(df.dtypes)
quantidade_elementos = list(df.count())
colunas = [0, 3, 9]
medias = [df.iloc[:, i].mean() for i in colunas]
desvios = [df.iloc[:, i].std() for i in colunas]
terceiro_quartil = [df.iloc[:, i].quantile(0.75) for i in colunas]
print(medias, desvios, terceiro_quartil)
resultados = {
    'num_linhas': num_linhas,
    'classes_colunas': classes_colunas,
    'quantidade_elementos': quantidade_elementos,
    'medias': medias,
    'desvios': desvios,
    'terceiro_quartil': terceiro_quartil
}
print(resultados)

[np.float64(548661.9371894961), np.float64(731478.0068460993), np.float64(778.7908036250478)] [np.float64(259912.9264939009), np.float64(17523003.588415086), np.float64(47879.79452114161)] [np.float64(774252.0), np.float64(0.0), np.float64(0.0)]
{'num_linhas': 36634, 'classes_colunas': [dtype('int64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64')], 'quantidade_elementos': [36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634, 36634], 'medias': [np.float64(548661.9371894961), np.float64(731478.0068460993), np.float64(778.7908036250478)], 'desvios': [np.float64(259912.9264939009), np.float64(17523003.588415086), np.float64(47879.79452114161)], 'terceiro_quartil': [np.float64(774252.0), np.float64(0.0), np.float64(0.0)]}